name: xauusd_signal_app
description: A modern XAUUSD trading signal application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  provider: ^6.0.5
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^15.1.0+1
  candlesticks: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Add any assets or fonts here if needed

